import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ActivePlogs {
	public final static List<ClanMember> list = new ArrayList<>(Arrays.asList(
			new ClanMember("Neyka"),
			new ClanMember("Dezra Nyx"),
			new ClanMember("Chaika Senpai"),
			new ClanMember("HeroVader"),
			new ClanMember("Lil SweetPea"),
			new ClanMember("hayapi"),
			new ClanMember("Riley Delirium"),
			new ClanMember("Coko"),
			new ClanMember("Tinge I"),
			new ClanMember("Sugartits"),
			new ClanMember("yaak"),
			new ClanMember("Koyol"),
			new ClanMember("Sybil Reisz"),
			new ClanMember("EveL Antagonist"),
			new ClanMember("Yôna"),
			new ClanMember("TheMadman"),
			new ClanMember("fleance"),
			new ClanMember("Squïshy"),
			new ClanMember("ClaireHasumi"),
			new ClanMember("Niltaic"),
			new ClanMember("Pulcrits"),
			new ClanMember("Alyndaria"),
			new ClanMember("LunarxSky"),
			new ClanMember("Snakeyez"),
			new ClanMember("Siberian"),
			new ClanMember("Fangril"),
			new ClanMember("Spadow"),
			new ClanMember("Vasilyna"),
			new ClanMember("Morning Breath"),
			new ClanMember("Noxie Pie"),
			new ClanMember("Shuza"),
			new ClanMember("Memnock"),
			new ClanMember("Zumchi"),
			new ClanMember("Geffenia"),
			new ClanMember("grossegraine"),
			new ClanMember("imKaty"),
			new ClanMember("Toon Kaiz"),
			new ClanMember("anna ae"),
			new ClanMember("SnyperLyfe"),
			new ClanMember("Tiear"),
			new ClanMember("xMana"),
			new ClanMember("WhiteIRabbit"),
			new ClanMember("GodTierMoan"),
			new ClanMember("Kyutsuki"),
			new ClanMember("Notorious LAG"),
			new ClanMember("Yüii"),
			new ClanMember("Snakeyees"),
			new ClanMember("erzaaachann"),
			new ClanMember("Bahumat"),
			new ClanMember("LeeXiaoZhang"),
			new ClanMember("Inori Waifu"),
			new ClanMember("Aarvak"),
			new ClanMember("Queenikkok"),
			new ClanMember("datfoig"),
			new ClanMember("Neyka Darksoul"),
			new ClanMember("KeriKoroshimasu"),
			new ClanMember("SilverWingedAngel"),
			new ClanMember("Einalise"),
			new ClanMember("Flaming Homosexual"),
			new ClanMember("BD Pulcrit"),
			new ClanMember("Sehrala"),
			new ClanMember("Zonet"),
			new ClanMember("WolfgangSai"),
			new ClanMember("ZoneOFblade"),
			new ClanMember("True Emperor"),
			new ClanMember("Elisa Aoi"),
			new ClanMember("FeelsAliMan"),
			new ClanMember("Fahn"),
			new ClanMember("Lia Revans"),
			new ClanMember("GrosShaft"),
			new ClanMember("Alicia OuO"),
			new ClanMember("tmags"),
			new ClanMember("Sekaî"),
			new ClanMember("Rinaa"),
			new ClanMember("Lobitax"),
			new ClanMember("imELSV"),
			new ClanMember("LiviaChu")));
}
